version: '3.8'

services:
  # Servicio de base de datos MySQL
  mysql:
    image: mysql:8.0
    container_name: trade-simulator-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Bolsa
      MYSQL_USER: usuario
      MYSQL_PASSWORD: password
    volumes:
      # Volumen bind mount para persistir datos de MySQL
      - ./sources/servidorNode/database:/docker-entrypoint-initdb.d
      # Volumen para datos de MySQL
      - mysql_data:/var/lib/mysql
    networks:
      - backend_network
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Servicio de backend Node.js
  node:
    build:
      context: ./sources/servidorNode
      dockerfile: Dockerfile
    container_name: trade-simulator-node
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      # Volumen bind mount para código fuente de Node.js
      - ./sources/servidorNode:/app
      # Excluir node_modules del host
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DB_HOST=mysql
      - DB_USER=usuario
      - DB_PASS=password
      - DB_NAME=Bolsa
      - DB_PORT=3306
    networks:
      - backend_network
      - frontend_network
    ports:
      - "3000:3000"

  # Servicio de frontend Angular
  angular:
    build:
      context: ./sources/frontendAngular
      dockerfile: Dockerfile
    container_name: trade-simulator-angular
    restart: unless-stopped
    depends_on:
      - node
    volumes:
      # Volumen bind mount para código fuente de Angular
      - ./sources/frontendAngular:/app
      # Excluir node_modules del host
      - /app/node_modules
    networks:
      - frontend_network
    ports:
      - "4200:4200"

# Definición de volúmenes
volumes:
  mysql_data:
    driver: local

# Definición de redes
networks:
  # Red para conectar MySQL y Node.js
  backend_network:
    driver: bridge
  # Red para conectar Node.js y Angular
  frontend_network:
    driver: bridge