services:
    db:
      image: mysql
      container_name: db
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: Bolsa
      volumes:
        - db_datos:/var/lib/mysql
      networks:
        red_backend:
          ipv4_address: 192.168.1.3
    
    backend:
      build:
        context: .
        dockerfile: servidorDocker
      container_name: backend
      depends_on:
        - db
      networks:
        red_backend:
          ipv4_address: 192.168.1.2
        red_frontend:
          ipv4_address: 192.168.2.2
      command: ["wait-for-it.sh", "192.168.1.3:3306", "--timeout=45", "--", "node", "app.js"]
    
    frontend:
      build:
        context: .
        dockerfile: frontendDocker
      container_name: frontend
      depends_on:
        - backend
      networks:
        red_frontend:
          ipv4_address: 192.168.2.3
      command: ["ng","serve","--host","0.0.0.0"]
      ports:
        - "4200:4200"

volumes:
  db_datos:
    driver: local

networks:
  red_backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24

  red_frontend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.2.0/24
